min_section_char_count = 20
min_sentence_in_section = 2
max_section_formulas_count = 3
max_section_code_snipet_count = 2
min_valid_section_count = 3 # This includes preface section
min_words_in_sentence = 2
min_valid_section_percentage = 0.2
max_list_in_section_percentage = 0.5
max_words_in_sentence_with_backslash_n = 45